apiVersion: v1
kind: Service
metadata:
  name: pyapp-service
spec:
  ports:
  - port: 31001
    nodePort: 31001
    targetPort: app-port
    protocol: TCP
  selector:
    app: pyapp
  type: LoadBalancer
